### ISSUE TITLE
iqdb报错

### ISSUE THREAD

**Issue by chinoll** [kitUIN/PicImageSearch#11]
如下图
![image](https://user-images.githubusercontent.com/22575232/147573181-66f6439b-d333-4e05-a042-b259d159143a.png)

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/147669452-dceece5f-ef97-4847-9153-53350977350f.png)
已修复
`pip3 install PicImageSearch --upgrade` 更新到最新版本
