### ISSUE TITLE
百度识图在一些情况下报错 TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Container-Zero** [kitUIN/PicImageSearch#114]
Python Version：`3.10.11`

![image](https://github.com/kitUIN/PicImageSearch/assets/20435019/6d4c35af-d5c9-4d9b-9a59-8d7fe71762f1)

demo的默认设置下不存在问题，但如果开启url处理，并将其替换成一些其它连接，则有概率触发上述错误

复现：
1.将百度demo中，第11行的`url`替换成： https://gchat.qpic.cn/gchatpic_new/0/0-0-A744FA08A2083AD5BDBE319EB69ED8B1/0 
2.解除第19行使用`url`的注释
3.注释第20行
4.出现上述报错

**Comment by kitUIN** [comment]
该bug应该是由于搜索不到相似图片导致的

**Comment by Container-Zero** [comment]
https://github.com/kitUIN/PicImageSearch/assets/20435019/a237e366-9cbf-43f8-9f3a-5027563b3bb6
https://github.com/kitUIN/PicImageSearch/assets/20435019/18139794-5cd3-4462-a4e1-07d958921612

我遇到的情况还蛮奇怪的，这是两张一模一样的图片，区别只是一个被压缩过一个没有被压缩过，他们目前体积不一样，但分辨率一致
现在的情况是：
1.第一条超链接可以被百度正常检索
2.第二条超链接会触发上述bug，也就是您所说的搜索不到相似图片导致

百度搜索为何对图片变动如此敏感？根据我的测试这种情况还蛮常发生的，目前看来百度的可靠性似乎并不高。

**Comment by NekoAria** [comment]
你的结论是对的，百度搜图的可靠性不高。
不过，目前这个库对百度搜图结果的解析逻辑也确实存在问题，我稍微修正了下。
最后，因为我不用百度，所以没什么动力继续优化解析逻辑，例如实现加载下一页功能等。

**Comment by Container-Zero** [comment]
> 你的结论是对的，百度搜图的可靠性不高。 不过，目前这个库对百度搜图结果的解析逻辑也确实存在问题，我稍微修正了下。 最后，因为我不用百度，所以没什么动力继续优化解析逻辑，例如实现加载下一页功能等。

好的

**Comment by NekoAria** [comment]
done 942a49f4
