### ISSUE TITLE
ascii2d到底是我被屏蔽了还是寄了

### ISSUE THREAD

**Issue by CCYellowStar2** [kitUIN/PicImageSearch#138]
![725224167745acfe1e540e03580687a8](https://github.com/kitUIN/PicImageSearch/assets/149048350/1b4ed851-d41a-43af-93d0-ece67badef2f)

**Comment by NekoAria** [comment]
寄了，昨天恢复了。

[落ちてます - 4 天前](https://twitter.com/ascii2d/status/1789255549516693775)
[復旧は早くても火曜日の夕方ぐらいです - 3 天前](https://twitter.com/ascii2d/status/1789666426497990705)
[検索は復帰 - 昨天](https://twitter.com/ascii2d/status/1790368389606810010)
