### ISSUE TITLE
Tracemoe搜索的标题都是None，ascii2d的文字编码是encoding

### ISSUE THREAD

**Issue by banned2054** [kitUIN/PicImageSearch#14]
tracemoe.search()除了图片地址还要什么参数吗，搜索的动漫标题都是None的，
还有现在res.raw[0].titile是dict了，要不要改一下文档。
ascii2d编码是不是有问题，搜索出的文字都是from_encoding的，直接被我的程序忽略掉了。
![~(1IY`6SS60@O %Q3W`E9HL](https://user-images.githubusercontent.com/34962009/152793635-20316854-e0c0-4597-8c56-b01aec719b41.png)

**Comment by kitUIN** [comment]
1.tracemoe.search()确实只需要图片地址 至于你说的动漫标题都是None，可以将报错与源码展示下吗？
2.文档问题，将会在之后修改，感谢提醒
3.ascii2d编码的warning对实际输出不影响，如果觉得输出难看，可以在`ascii2d.py`的36行更改为
![image](https://user-images.githubusercontent.com/68675068/152925229-e3dd9837-707c-4848-b78f-4b40e5577da9.png)

**Comment by banned2054** [comment]
1.源码是这个样子的，没有出现报错，
![image](https://user-images.githubusercontent.com/34962009/152935506-a5499fb2-326b-413f-9825-bb56cf7da241.png)
我是想将搜图添加到qq机器人里，然后所出来的动画标题都是None的，各种语言版本的标题都是None，就像这样
![image](https://user-images.githubusercontent.com/34962009/152936743-7ef052ca-9fa2-4b94-8dfd-b3ab414e9fc0.png)
3.如果只是警告我可能不会发这条issue,我现在用ascii2d搜索twitter的图片能得到结果，但是没有作者和url地址，用了像这样的测试方法
![image](https://user-images.githubusercontent.com/34962009/152938800-486c0893-31b2-4e1f-b364-21a47dd0b2b4.png)
输出的结果是什么都没有
![image](https://user-images.githubusercontent.com/34962009/152938949-e4d2093e-ba80-449f-af1f-4b7e3a7a0c2b.png)
机器人输出的结果也没有作者和url地址，但有缩略图
![image](https://user-images.githubusercontent.com/34962009/152939023-8a09a37a-0153-4ef7-bdf9-247b12c026e0.png)

**Comment by kitUIN** [comment]
问题1 已经解决
`pip3 install PicImageSearch==2.2.6`升级或者使用`pip3 install PicImageSearch --upgrade`
问题2 能否提供图片让我重现错误

**Comment by kitUIN** [comment]
我这边测试都没问题，能否提供能导致错误的图片地址？

**Comment by banned2054** [comment]
抱歉，下午外出了，刚刚才回来，这是源码
![image](https://user-images.githubusercontent.com/34962009/152988328-5ab25573-3dad-47e0-af9d-ce17f1aae41d.png)
这个是搜索的图片
![T{`O90K BTI{{5N P5BZ778](https://user-images.githubusercontent.com/34962009/152988376-c26e886a-cfb8-4695-8b1f-8689797784f5.jpg)

**Comment by banned2054** [comment]
encoding = None那个参数是后面加的，加这个和没加没有区别

**Comment by kitUIN** [comment]
`raw[0]`所谓的有可能为空不是指为`None`
而是指内部的url 作者 标题为空
![image](https://user-images.githubusercontent.com/68675068/152998169-b56f3dc3-6bae-48b8-a51e-f03d0816ad56.png)
看来是我文档写的不明白，
不建议对`raw[0]`判空，建议对`res.raw[0].url`进行判空
根据你写的应该这么判断:
```
if result.url == "":
	result = res.raw[1]

```
(PS:判断`None` 我个人建议用`if res is None`)

**Comment by banned2054** [comment]
现在没有问题了，除了搜索时间很慢，可能是我2c2g的服务器性能太弱了。还有就是搜索结果不准，不过我自己去网站搜也只能搜到一样的结果。
总之目前没有问题了，感谢~
