### ISSUE TITLE
Other engines

### ISSUE THREAD

**Issue by Peloxerat** [kitUIN/PicImageSearch#157]
What are your thoughts on adding new, specialized search engines like Alibaba, 123rf, and Wildberries? Would it be worthwhile, or just clutter the codebase with unnecessary features? I'm trying to gauge if it makes sense to invest the development time in this idea.

**Comment by NekoAria** [comment]
Adding these new search engines might involve dealing with many complex situations and understanding how many users would actually need them. Our library's main job is not to do the searches but to give back the results after the search. So, adding a new search engine isn't as simple as with [search-by-image](https://github.com/dessant/search-by-image).

---

Feel free to adjust any details if needed.
