### ISSUE TITLE
去除 `cloudscraper` 后改用 `httpx` ，似乎并没有触发 cf

### ISSUE THREAD

**Issue by NekoAria** [kitUIN/PicImageSearch#17]
因为我只在我的机器和服务器上测试过，所以不太确定。
于是创建了一个新的分支：https://github.com/NekoAria/PicImageSearch/tree/httpx-only
@Coder-Sakura @Ansbot @kitUIN 
请各位帮忙测试一下。

**Comment by NekoAria** [comment]
并且我之前用的是异步的 `ascii2d` ，那个请求就是用 `httpx` 封装的，而 #13 里提到的应该是同步的 `ascii2d` 。

**Comment by kitUIN** [comment]
居然报了302
![image](https://user-images.githubusercontent.com/68675068/158340130-d9ae572f-0bc1-4161-8fc8-45f7a1a58dd7.png)

**Comment by NekoAria** [comment]
> 居然报了302 ![image](https://user-images.githubusercontent.com/68675068/158340130-d9ae572f-0bc1-4161-8fc8-45f7a1a58dd7.png)

可是异步的我没动啊。。。动的是同步的

**Comment by kitUIN** [comment]
> > 居然报了302 ![image](https://user-images.githubusercontent.com/68675068/158340130-d9ae572f-0bc1-4161-8fc8-45f7a1a58dd7.png)
> 
> 可是异步的我没动啊。。。动的是同步的

看来是我的问题....

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/158343152-4120a318-2c71-48c5-8532-e3248d80a991.png)
我服务器端不行

**Comment by NekoAria** [comment]
> ![image](https://user-images.githubusercontent.com/68675068/158343152-4120a318-2c71-48c5-8532-e3248d80a991.png) 我服务器端不行

那异步的也不行吗？如果是的话，异步的也得改为用 `cloudscraper` 。

**Comment by NekoAria** [comment]
不过从https://github.com/Tsuk1ko/cq-picsearcher-bot/issues/283最后的回复来看，只需要指定TLS版本就行。

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/158350387-55b57634-5eb5-4097-be49-4c55bd6a4906.png)
重开环境测试后两者皆无问题

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/158351437-fa695d80-e5a9-41af-9c4d-51cffd261197.png)
多次请求时同步时不时出错.
异步暂时无问题

**Comment by NekoAria** [comment]
> ![image](https://user-images.githubusercontent.com/68675068/158351437-fa695d80-e5a9-41af-9c4d-51cffd261197.png) 多次请求时同步时不时出错. 异步暂时无问题

实际上我测试过换成 `httpx` 之前的代码，同步的也是时不时出错，而且不仅是 `ascii2d` ，其他的也有这情况，最明显的是 `iqdb` 。

**Comment by NekoAria** [comment]
目前已经合并进主分支，如果遇到问题到时候再开新 issue
