### ISSUE TITLE
百度识图的问题

### ISSUE THREAD

**Issue by Wqn321** [kitUIN/PicImageSearch#21]
作者你好，我在使用百度识图的时候会出现这个问题，请问该怎么解决
<img width="806" alt="image" src="https://user-images.githubusercontent.com/73831711/161072123-daa7d59a-a88e-4034-a057-e761ff883c25.png">

**Comment by kitUIN** [comment]
> 作者你好，我在使用百度识图的时候会出现这个问题，请问该怎么解决
> <img width="806" alt="image" src="https://user-images.githubusercontent.com/73831711/161072123-daa7d59a-a88e-4034-a057-e761ff883c25.png">
> 

使用异步还是同步，请贴出源码，我们需要重现该错误才能判断情况
