### ISSUE TITLE
求助，大佬，部分服务器会重定向到这个‘在转到 Google 之前’界面，除了proxy还有什么参数可以跳过呢？

### ISSUE THREAD

**Issue by sklfihggczx** [kitUIN/PicImageSearch#214]
服务器访问谷歌跳转到‘在转到 Google 之前‘界面 该怎么设置呢？
![image](https://github.com/user-attachments/assets/f98cd5c8-2055-4006-bbaf-e0ddb12c8889)
这个界面是从network 235行获取的
![image](https://github.com/user-attachments/assets/9a074688-5c0c-43e4-ade2-b0bb5024ce16)

求助！

**Comment by NekoAria** [comment]
没有

**Comment by AiraNadih** [comment]
这个问题不好说，除非能复现你遇到的情况。

不过你可以试试：

- 把你浏览器里的 cookies 传进去
- 或者加上完整的 headers

前提是你用浏览器访问 Google 搜图时，要么不弹这个窗口，要么点了 全部接受 / 全部拒绝 按钮后能正常使用。
