### ISSUE TITLE
lenso.ai

### ISSUE THREAD

**Issue by Peloxerat** [kitUIN/PicImageSearch#222]
I found a new engine that searches surprisingly well, which really impressed me.
https://lenso.ai/

I think I could implement the search, but there are several issues. The company appeared very recently, [about 4 months ago](https://www.reddit.com/r/roastmystartup/comments/1dpkuom/roast_lensoai_ai_reverse_image_search_and_face/), and I think their functionality might change significantly in the near future.
I also discovered that they don't have an official API yet, so I'm not sure I can implement the full site functionality based only on traffic analysis.
![image](https://github.com/user-attachments/assets/3c9d224e-3d9c-44e6-a03c-fe7c32b85a74)

Although, there isn't really that much data. It's like everywhere else: `thumbnail, source_url, image_url, title, lang`

So I wanted to get advice - is the site worth implementing or not? My opinion is that the site is really good.

**Comment by NekoAria** [comment]
Based on testing only the images in the `demo` directory, the search functionality seems fairly good.

However, I noticed that after more than 10 searches, it prompts that the daily free search limit has been reached.
Currently, this only appears as a modal on the webpage and doesn’t actually restrict further searches, so searches can still continue.
That said, it’s possible they might strengthen this limitation in the future to enforce a strict “10 free searches per IP address per day” rule.

Additionally, I couldn’t find any part on the webpage that included `source_url`, which somewhat limits usability in my opinion.

**Comment by NekoAria** [comment]
BTW, I reviewed the Reddit post referenced in the screenshot you shared and discovered an interesting reverse image search engine: [Pimeyes](https://pimeyes.com).

I tried it out and found its search results to be incredibly impressive.
Of course, it seems to be primarily suitable for finding real people.
Specifically, it can be used to locate certain models or actors.

**Comment by Peloxerat** [comment]
I indicated the link, maybe not explicitly. Well, it's not the point.
![image](https://github.com/user-attachments/assets/260157ff-ef45-402a-8940-38f5d57d0246)


I also didn't find the URL search at first, but it exists.
https://lenso.ai/en/search-by-url?url=url?raw=true&utm_campaign=plagiarismdetector&utm_medium=affiliate&utm_source=affiliate
Then click the button in the middle

If doing it with requests, you first need to make a POST request to https://lenso.ai/api/upload/process/url with the specified URL in the request body, which gives us an ID that we can use to search on https://lenso.ai/api/search
But there's another problem here. To make such a request, we'll need the base64 of the image (as I understood, it's mandatory). So it requires 3 requests when searching by URL! And that's quite a lot, I think.
1 - POST https://lenso.ai/api/upload/process/url
2 - GET request to obtain the base64 image from URL
3 - POST https://lenso.ai/api/search

By the way, searching by file requires 2 requests
1 - POST https://lenso.ai/api/upload where we pass base64
2 - POST https://lenso.ai/api/search where we pass base64 and id

I also learned that if there will be search implementation, it will be done using next_page and pre_page, like it's done in Google and TinEye
It's quite stressful for just one engine. Also don't forget that there can be multiple pages in duplicates (or related or similar) if there are too many results.


translated with 3.5 Sonnet

**Comment by NekoAria** [comment]
Apologies, I hadn’t looked closely before and didn’t notice you included the link to the Reddit post where the conversation in your screenshot came from.

To be honest, as things currently stand, services like Lenso.ai and Pimeyes may indeed deliver decent search results, but much of the relevant information—such as the website where the images appear—requires a paid subscription to access.

Therefore, I don’t think wrapping them as an API for inclusion in this library would be very ideal.

**Comment by Peloxerat** [comment]
I didn't notice that there were encrypted links...
I saw that the results showed correct domains, but for some reason I never clicked on them.
Here, for example, what it shows for test01.jpg: https://photo.99px.ru/JHKRH
Correct : https://photo.99px.ru/photos/343598/

Results are encrypted, so then there really is no point to this engine

**Comment by Peloxerat** [comment]
> BTW, I reviewed the Reddit post referenced in the screenshot you shared and discovered an interesting reverse image search engine: [Pimeyes](https://pimeyes.com).

If you are interested, there is a similar service. It also does not show the URL, also for money..
https://facecheck.id/
