### ISSUE TITLE
一些特殊的需求

### ISSUE THREAD

**Issue by chinoll** [kitUIN/PicImageSearch#25]
能不能内置DNS（使用DoH来解析IP），在某些地方一些搜图网站可能会遭到DNS污染

**Comment by NekoAria** [comment]
aiohttp 倒是有相关的库可以用， httpx 好像没有。
我之前是有想过用 aiohttp 替换 httpx ，不过问题在于那个同步魔改似乎失效了。
所以也就作罢了。
如果能保留同步，不需要区分维护同步和异步，还能替换到 aiohttp ，那就很简单。

**Comment by chinoll** [comment]
> aiohttp 倒是有相关的库可以用， httpx 好像没有。 我之前是有想过用 aiohttp 替换 httpx ，不过问题在于那个同步魔改似乎失效了。 所以也就作罢了。 如果能保留同步，不需要区分维护同步和异步，还能替换到 aiohttp ，那就很简单。

似乎可行，关闭SSL，直接用IP访问就行了

**Comment by NekoAria** [comment]
> > aiohttp 倒是有相关的库可以用， httpx 好像没有。 我之前是有想过用 aiohttp 替换 httpx ，不过问题在于那个同步魔改似乎失效了。 所以也就作罢了。 如果能保留同步，不需要区分维护同步和异步，还能替换到 aiohttp ，那就很简单。
> 
> 似乎可行，关闭SSL，直接用IP访问就行了

能写个 demo 或者伪代码看看吗？

**Comment by NekoAria** [comment]
搞明白之前为什么尝试替代 httpx 失败了。
现在全面换成 aiohttp 了，后续可以增加 socks 代理支持和 DoH 支持。

**Comment by chinoll** [comment]
- [ ] 防止DNS污染
- [ ] 防止SNI阻断

**Comment by chinoll** [comment]
似乎，一直在报SSL错误了。
有没有办法解决

**Comment by NekoAria** [comment]
> 似乎，一直在报SSL错误了。 有没有办法解决

暂时不知道怎么解决，之后再说吧（
