### ISSUE TITLE
新版构建失败

### ISSUE THREAD

**Issue by chinoll** [kitUIN/PicImageSearch#27]
python版本问题？
![image](https://user-images.githubusercontent.com/22575232/177193548-43d1b96c-efa3-496e-b03e-1686a2f1f618.png)

**Comment by NekoAria** [comment]
那升级一下 Python 版本（

**Comment by chinoll** [comment]
> 那升级一下 Python 版本（

pyproject.toml里的版本升级到3.7就没问题了
3.6一直构建出错
