### ISSUE TITLE
exhentai文档是不是有问题

### ISSUE THREAD

**Issue by banned2054** [kitUIN/PicImageSearch#34]
![image](https://user-images.githubusercontent.com/34962009/186935154-ef569a77-5859-45f8-a5d1-0e5aedf6c9df.png)
![image](https://user-images.githubusercontent.com/34962009/186935279-a6941852-6f29-42e7-814e-7f5e3d13b4f5.png)

**Comment by NekoAria** [comment]
应该没问题吧，能把你这个 response.url 发一下吗？

**Comment by banned2054** [comment]
https://exhentai.org/?f_shash=23ff88d7125a482fc1dc86af95c579275f16069a;monotone&fs_from=RJ402514_0_001.jpg&fs_similar=on

**Comment by banned2054** [comment]
原来不需要origin吗，我本来打算先看看origin的内容是啥

**Comment by NekoAria** [comment]
大概是网络超时了吧
你往 Network 的参数里添加 `timeout=60` 再看看
