### ISSUE TITLE
百度识图报错

### ISSUE THREAD

**Issue by rookiexiao123** [kitUIN/PicImageSearch#7]
hi，我在用百度识图的api，但是报错了，AttributeError: 'BaiDuResponse' object has no attribute 'same'.作者能帮忙看看么？

**Comment by kitUIN** [comment]
![image](https://user-images.githubusercontent.com/68675068/118354092-fe8ace00-b59b-11eb-9b4b-550734ad1d5a.png)
`AttributeError: 'BaiDuResponse' object has no attribute 'same'`指api返回中没有该值  
简单来说就是它搜不到结果

**Comment by rookiexiao123** [comment]
谢谢，非常感谢。我还有一个问题想请教一下，就是我得到的url打开就是相似图片。我在百度识图里面会出现相关商品，图片来源，相似图片。怎么可以爬到相关商品和图片来源的信息呢？

**Comment by nymanyim** [comment]
1.考虑使用hasattr(BaiDuResponse, 'same')来判断same属性是否存在
2.测试文件报错，接口失效了吗
![image](https://user-images.githubusercontent.com/54471703/128445076-ccf0554e-2b67-4095-914b-39c75c0e05b3.png)

**Comment by nymanyim** [comment]
![image](https://user-images.githubusercontent.com/54471703/128446025-476c7011-f7d2-4c82-a49d-e89bfaf86ed1.png)

**Comment by kitUIN** [comment]
测试文件默认是展示搜索到的图片来源，用过百度识图的应该知道有的时候他是找不到图片来源的，这时候`res.raw`列表为空，仅`res.similar`列表存有数据
![image](https://user-images.githubusercontent.com/68675068/128681402-1b0bc0d2-7a6c-43ee-a9bc-7bfb69a4275f.png)

**Comment by Wqn321** [comment]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/73831711/157237676-d612fea2-d4e3-4fac-bb04-0d06ce0b01ea.png">

**Comment by Wqn321** [comment]
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/73831711/157237887-de77cabc-7716-473a-a846-7463c8d838f3.png">
运行百度识图的demo 的时候会有这样的报错，该怎么解决啊，作者能看下嘛

**Comment by kitUIN** [comment]
> <img alt="image" width="1171" src="https://user-images.githubusercontent.com/73831711/157237887-de77cabc-7716-473a-a846-7463c8d838f3.png">
> 
> 运行百度识图的demo 的时候会有这样的报错，该怎么解决啊，作者能看下嘛

百度更改了搜索需要的参数，目前暂时无法使用。
