### ISSUE TITLE
rework readme

### ISSUE THREAD

**Issue by Peloxerat** [kitUIN/PicImageSearch#91]
Once upon a time I found your library when it first started, back then there was only Chinese translate, and because of this it was quite difficult to figure out what was responsible for what

I made three translations of the readme file and demo files. I don't know Chinese so double check
[PicImageSearch-main_extended.zip](https://github.com/kitUIN/PicImageSearch/files/13599077/PicImageSearch-main_extended.zip)

**Comment by NekoAria** [comment]
Thank you for your contributions.

If it's convenient for you, could you please fork this repository, commit your changes to the README and demo files, and then create a pull request? This process will facilitate an easier review and any necessary modifications.

We appreciate your efforts in making these translations and look forward to your pull request.
